language: php
php:
  - '7.0'
services:
  - redis-server
before_install:
  - tests/travis.phpredis.sh
  - redis-cli info | grep version
  - composer install --dev --prefer-source --no-interaction
script:
  - phpunit --coverage-text
